"""removing bio column

Revision ID: 3c39f378caae
Revises: 185557525327
Create Date: 2025-12-28 00:48:36.693925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c39f378caae'
down_revision: Union[str, Sequence[str], None] = '185557525327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
